<?php
/*******************************************************************
 * [pugoin] (C)2010 - 2099 Dream3 Inc.
 *
 * This is NOT a freeware, use is subject to license terms
 *
 * @Filename db_tb_datas.php $
 *
 * @Author http://www.pugo.in $
 *
 * @Date 2011-09-16 17:25:37 9142602 593652850 85956 $
 *******************************************************************/

 $db_tb_datas = array (
  'role_module' => 
  array (
    'key' => 'module',
    'datas' => 
    array (
      0 => 
      array (
        'module' => 'role_action',
        'name' => '动作权限管理',
      ),
      1 => 
      array (
        'module' => 'role',
        'name' => '角色设置',
      ),
      2 => 
      array (
        'module' => 'login',
        'name' => '登录',
      ),
      3 => 
      array (
        'module' => 'index',
        'name' => '首页',
      ),
      4 => 
      array (
        'module' => 'pm',
        'name' => '消息管理',
      ),
      5 => 
      array (
        'module' => 'setting',
        'name' => '系统设置',
      ),
      6 => 
      array (
        'module' => 'link',
        'name' => '友情链接设置',
      ),
      7 => 
      array (
        'module' => 'role_module',
        'name' => '动作模块设置',
      ),
      8 => 
      array (
        'module' => 'db',
        'name' => '数据库管理',
      ),
      9 => 
      array (
        'module' => 'show',
        'name' => '界面与显示设置',
      ),
      10 => 
      array (
        'module' => 'robot',
        'name' => '蜘蛛爬行记录',
      ),
      11 => 
      array (
        'module' => 'tag',
        'name' => 'TAG管理',
      ),
      12 => 
      array (
        'module' => 'report',
        'name' => '举报管理',
      ),
      13 => 
      array (
        'module' => 'topic',
        'name' => '微博管理',
      ),
      14 => 
      array (
        'module' => 'ucenter',
        'name' => 'Ucenter整合',
      ),
      15 => 
      array (
        'module' => 'cache',
        'name' => '缓存管理',
      ),
      16 => 
      array (
        'module' => 'upgrade',
        'name' => '系统升级',
      ),
      17 => 
      array (
        'module' => 'profile',
        'name' => '个人资料',
      ),
      18 => 
      array (
        'module' => 'member',
        'name' => '用户管理',
      ),
      19 => 
      array (
        'module' => 'income',
        'name' => '广告管理',
      ),
      20 => 
      array (
        'module' => 'notice',
        'name' => '网站公告',
      ),
      21 => 
      array (
        'module' => 'xwb',
        'name' => '新浪微博',
      ),
      22 => 
      array (
        'module' => 'vote',
        'name' => '投票',
      ),
      23 => 
      array (
        'module' => 'share',
        'name' => '分享',
      ),
      24 => 
      array (
        'module' => 'imjiqiren',
        'name' => 'QQ机器人',
      ),
      25 => 
      array (
        'module' => 'sms',
        'name' => '手机短信',
      ),
      26 => 
      array (
        'module' => 'task',
        'name' => '计划任务',
      ),
      27 => 
      array (
        'module' => 'user_tag',
        'name' => '个人标签',
      ),
      28 => 
      array (
        'module' => 'web_info',
        'name' => '关于我们',
      ),
      29 => 
      array (
        'module' => 'qun',
        'name' => '微群',
      ),
      30 => 
      array (
        'module' => 'sessions',
        'name' => '在线人数',
      ),
      31 => 
      array (
        'module' => 'medal',
        'name' => '勋章(用户荣誉)',
      ),
      32 => 
      array (
        'module' => 'vipintro',
        'name' => 'VIP认证',
      ),
      33 => 
      array (
        'module' => 'theme',
        'name' => '个人模板',
      ),
      34 => 
      array (
        'module' => 'search',
        'name' => '搜索',
      ),
      35 => 
      array (
        'module' => 'tools',
        'name' => '工具',
      ),
      36 => 
      array (
        'module' => 'other',
        'name' => '其他',
      ),
      37 => 
      array (
        'module' => 'settings',
        'name' => '设置',
      ),
      38 => 
      array (
        'module' => 'event',
        'name' => '活动',
      ),
      39 => 
      array (
        'module' => 'plugin',
        'name' => '插件',
      ),
      40 => 
      array (
        'module' => 'wall',
        'name' => '微博墙',
      ),
      41 => 
      array (
        'module' => 'fenlei',
        'name' => '分类',
      ),
      42 => 
      array (
        'module' => 'api',
        'name' => 'API',
      ),
    ),
  ),
  'role_action' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '88',
        'name' => '进入后台',
        'module' => 'index',
        'action' => '*',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      1 => 
      array (
        'id' => '92',
        'name' => '查看URL地址设置',
        'module' => 'setting',
        'action' => 'modify_rewrite',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      2 => 
      array (
        'id' => '7',
        'name' => '发表微博',
        'module' => 'topic',
        'action' => 'add|do_add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      3 => 
      array (
        'id' => '8',
        'name' => '查看角色列表',
        'module' => 'role',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      4 => 
      array (
        'id' => '9',
        'name' => '修改角色权限',
        'module' => 'role',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      5 => 
      array (
        'id' => '11',
        'name' => '所有动作列表',
        'module' => 'role_action',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      6 => 
      array (
        'id' => '13',
        'name' => '查看核心设置',
        'module' => 'setting',
        'action' => 'modify_normal',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      7 => 
      array (
        'id' => '50',
        'name' => '登录系统',
        'module' => 'login',
        'action' => 'dologin',
        'describe' => '',
        'message' => '',
        'allow_all' => '1',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      8 => 
      array (
        'id' => '51',
        'name' => '退出系统',
        'module' => 'login',
        'action' => 'logout',
        'describe' => '',
        'message' => '',
        'allow_all' => '1',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      9 => 
      array (
        'id' => '186',
        'name' => '执行删除标签操作',
        'module' => 'tag',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      10 => 
      array (
        'id' => '182',
        'name' => '编辑微博',
        'module' => 'topic',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      11 => 
      array (
        'id' => '183',
        'name' => '删除微博',
        'module' => 'topic',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      12 => 
      array (
        'id' => '176',
        'name' => '发送短信',
        'module' => 'pm',
        'action' => 'send|dosend',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      13 => 
      array (
        'id' => '187',
        'name' => '执行添加用户操作',
        'module' => 'member',
        'action' => 'doadd',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      14 => 
      array (
        'id' => '188',
        'name' => '编辑用户',
        'module' => 'member',
        'action' => 'search',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      15 => 
      array (
        'id' => '138',
        'name' => '分模块动作列表',
        'module' => 'role_action',
        'action' => 'list_action',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      16 => 
      array (
        'id' => '84',
        'name' => '修改友情链接设置',
        'module' => 'link',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      17 => 
      array (
        'id' => '89',
        'name' => '动作的模块列表',
        'module' => 'role_module',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      18 => 
      array (
        'id' => '90',
        'name' => '提交数据库备份',
        'module' => 'db',
        'action' => 'doexport',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      19 => 
      array (
        'id' => '91',
        'name' => '修改核心设置',
        'module' => 'setting',
        'action' => 'domodify_normal',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      20 => 
      array (
        'id' => '93',
        'name' => '修改URL地址设置',
        'module' => 'setting',
        'action' => 'domodify_rewrite',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      21 => 
      array (
        'id' => '101',
        'name' => '修改动作设置',
        'module' => 'role_action',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      22 => 
      array (
        'id' => '102',
        'name' => '删除动作',
        'module' => 'role_action',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      23 => 
      array (
        'id' => '184',
        'name' => '删除消息',
        'module' => 'pm',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      24 => 
      array (
        'id' => '189',
        'name' => '修改广告设置',
        'module' => 'income',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      25 => 
      array (
        'id' => '106',
        'name' => '修改界面显示设置',
        'module' => 'show',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      26 => 
      array (
        'id' => '107',
        'name' => '解压缩数据备份包',
        'module' => 'db',
        'action' => 'importzip',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      27 => 
      array (
        'id' => '108',
        'name' => '开关蜘蛛统计',
        'module' => 'robot',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      28 => 
      array (
        'id' => '111',
        'name' => '修改内容过滤设置',
        'module' => 'setting',
        'action' => 'domodify_filter',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      29 => 
      array (
        'id' => '115',
        'name' => '修改IP访问控制',
        'module' => 'setting',
        'action' => 'domodify_access',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      30 => 
      array (
        'id' => '123',
        'name' => '执行数据库优化',
        'module' => 'db',
        'action' => 'dooptimize',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      31 => 
      array (
        'id' => '125',
        'name' => '查看内容过滤设置',
        'module' => 'setting',
        'action' => 'modify_filter',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      32 => 
      array (
        'id' => '126',
        'name' => '查看IP访问控制',
        'module' => 'setting',
        'action' => 'modify_access',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      33 => 
      array (
        'id' => '132',
        'name' => '导入数据恢复',
        'module' => 'db',
        'action' => 'doimport',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      34 => 
      array (
        'id' => '133',
        'name' => '查看数据恢复页面',
        'module' => 'db',
        'action' => 'import',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      35 => 
      array (
        'id' => '134',
        'name' => '删除数据库备份',
        'module' => 'db',
        'action' => 'dodelete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      36 => 
      array (
        'id' => '135',
        'name' => '查看UC整合配置',
        'module' => 'ucenter',
        'action' => 'ucenter',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      37 => 
      array (
        'id' => '136',
        'name' => '修改UC整合配置',
        'module' => 'ucenter',
        'action' => 'do_setting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      38 => 
      array (
        'id' => '137',
        'name' => '查看角色权限',
        'module' => 'role',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      39 => 
      array (
        'id' => '139',
        'name' => '动作设置',
        'module' => 'role_action',
        'action' => 'modify|domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      40 => 
      array (
        'id' => '154',
        'name' => '修改邮件发送设置',
        'module' => 'setting',
        'action' => 'do_modify_smtp',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      41 => 
      array (
        'id' => '158',
        'name' => '清空缓存',
        'module' => 'cache',
        'action' => '*',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      42 => 
      array (
        'id' => '159',
        'name' => '系统后台升级',
        'module' => 'upgrade',
        'action' => '*',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      43 => 
      array (
        'id' => '172',
        'name' => '执行举报管理',
        'module' => 'report',
        'action' => 'batch_process',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      44 => 
      array (
        'id' => '169',
        'name' => '禁止搜索引擎',
        'module' => 'robot',
        'action' => 'disallow0|disallow1',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      45 => 
      array (
        'id' => '190',
        'name' => '添加公告',
        'module' => 'notice',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      46 => 
      array (
        'id' => '191',
        'name' => '执行编辑公告操作',
        'module' => 'notice',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      47 => 
      array (
        'id' => '192',
        'name' => '添加角色',
        'module' => 'role',
        'action' => 'add|doadd',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      48 => 
      array (
        'id' => '193',
        'name' => '读取新浪微博内容',
        'module' => 'xwb',
        'action' => '__synctopic',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      49 => 
      array (
        'id' => '194',
        'name' => '读取新浪微博评论',
        'module' => 'xwb',
        'action' => '__syncreply',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      50 => 
      array (
        'id' => '195',
        'name' => '发起新的投票',
        'module' => 'vote',
        'action' => 'create',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      51 => 
      array (
        'id' => '196',
        'name' => '投票',
        'module' => 'vote',
        'action' => 'vote',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      52 => 
      array (
        'id' => '197',
        'name' => '转发微博',
        'module' => 'topic',
        'action' => 'forward',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      53 => 
      array (
        'id' => '198',
        'name' => '评论微博',
        'module' => 'topic',
        'action' => 'reply',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      54 => 
      array (
        'id' => '200',
        'name' => '查看积分设置',
        'module' => 'setting',
        'action' => 'modify_credits',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      55 => 
      array (
        'id' => '201',
        'name' => '修改积分设置',
        'module' => 'setting',
        'action' => 'do_modify_credits',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      56 => 
      array (
        'id' => '202',
        'name' => '查看积分规则列表',
        'module' => 'setting',
        'action' => 'list_credits_rule',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      57 => 
      array (
        'id' => '204',
        'name' => '修改积分规则',
        'module' => 'setting',
        'action' => 'do_modify_credits_rule',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      58 => 
      array (
        'id' => '205',
        'name' => '查看某项积分规则',
        'module' => 'setting',
        'action' => 'modify_credits_rule',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      59 => 
      array (
        'id' => '206',
        'name' => '删除站外调用',
        'module' => 'share',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      60 => 
      array (
        'id' => '208',
        'name' => '添加站外调用',
        'module' => 'share',
        'action' => 'add|do_add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      61 => 
      array (
        'id' => '210',
        'name' => '编辑站外调用',
        'module' => 'share',
        'action' => 'modify|domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      62 => 
      array (
        'id' => '211',
        'name' => '查看QQ微博设置',
        'module' => 'setting',
        'action' => 'modify_qqwb',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      63 => 
      array (
        'id' => '212',
        'name' => '修改QQ微博设置',
        'module' => 'setting',
        'action' => 'do_modify_qqwb',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      64 => 
      array (
        'id' => '213',
        'name' => '查看新浪微博设置',
        'module' => 'setting',
        'action' => 'modify_sina',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      65 => 
      array (
        'id' => '215',
        'name' => '查看邮件发送设置',
        'module' => 'setting',
        'action' => 'modify_smtp',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      66 => 
      array (
        'id' => '216',
        'name' => '查看远程附件设置',
        'module' => 'setting',
        'action' => 'modify_ftp',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      67 => 
      array (
        'id' => '217',
        'name' => '查看推荐话题',
        'module' => 'setting',
        'action' => 'modify_hot_tag_recommend',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      68 => 
      array (
        'id' => '218',
        'name' => '查看首页幻灯管理',
        'module' => 'setting',
        'action' => 'modify_slide_index',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      69 => 
      array (
        'id' => '219',
        'name' => '查看内页幻灯管理',
        'module' => 'setting',
        'action' => 'modify_slide',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      70 => 
      array (
        'id' => '220',
        'name' => '查看编辑用户页面',
        'module' => 'member',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      71 => 
      array (
        'id' => '221',
        'name' => '查看添加用户页面',
        'module' => 'member',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      72 => 
      array (
        'id' => '222',
        'name' => '查看数据备份页面',
        'module' => 'db',
        'action' => 'export',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      73 => 
      array (
        'id' => '223',
        'name' => '查看数据表优化页面',
        'module' => 'db',
        'action' => 'optimize',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      74 => 
      array (
        'id' => '224',
        'name' => '修改新浪微博设置',
        'module' => 'setting',
        'action' => 'do_modify_sina',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      75 => 
      array (
        'id' => '225',
        'name' => '修改QQ机器人设置',
        'module' => 'imjiqiren',
        'action' => 'do_modify_setting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      76 => 
      array (
        'id' => '226',
        'name' => '查看短信发送记录',
        'module' => 'sms',
        'action' => 'send_log',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      77 => 
      array (
        'id' => '227',
        'name' => '修改手机短信设置',
        'module' => 'sms',
        'action' => 'do_modify_setting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      78 => 
      array (
        'id' => '228',
        'name' => '查看短信接收记录',
        'module' => 'sms',
        'action' => 'receive_log',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      79 => 
      array (
        'id' => '229',
        'name' => '删除短信收发记录',
        'module' => 'sms',
        'action' => 'delete_log',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      80 => 
      array (
        'id' => '230',
        'name' => '查看微博列表',
        'module' => 'topic',
        'action' => 'modifylist',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      81 => 
      array (
        'id' => '231',
        'name' => '修改推荐话题',
        'module' => 'setting',
        'action' => 'do_modify_hot_tag_recommend',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      82 => 
      array (
        'id' => '232',
        'name' => '修改首页幻灯设置',
        'module' => 'setting',
        'action' => 'do_modify_slide_index',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      83 => 
      array (
        'id' => '233',
        'name' => '修改内页幻灯设置',
        'module' => 'setting',
        'action' => 'do_modify_slide',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      84 => 
      array (
        'id' => '234',
        'name' => '修改多个计划任务',
        'module' => 'task',
        'action' => 'dobatchmodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      85 => 
      array (
        'id' => '235',
        'name' => '查看计划任务',
        'module' => 'task',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      86 => 
      array (
        'id' => '236',
        'name' => '查看单个计划任务',
        'module' => 'task',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      87 => 
      array (
        'id' => '237',
        'name' => '修改单个计划任务',
        'module' => 'task',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      88 => 
      array (
        'id' => '238',
        'name' => '查看计划任务记录',
        'module' => 'task',
        'action' => 'log_list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      89 => 
      array (
        'id' => '239',
        'name' => '删除计划任务',
        'module' => 'task',
        'action' => 'log_delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      90 => 
      array (
        'id' => '240',
        'name' => '修改远程附件设置',
        'module' => 'setting',
        'action' => 'do_modify_ftp',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      91 => 
      array (
        'id' => '241',
        'name' => '查看投票',
        'module' => 'vote',
        'action' => 'edit',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      92 => 
      array (
        'id' => '242',
        'name' => '修改投票',
        'module' => 'vote',
        'action' => 'doedit',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      93 => 
      array (
        'id' => '243',
        'name' => '删除投票',
        'module' => 'vote',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      94 => 
      array (
        'id' => '244',
        'name' => '添加个人标签',
        'module' => 'user_tag',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      95 => 
      array (
        'id' => '245',
        'name' => '删除个人标签',
        'module' => 'user_tag',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      96 => 
      array (
        'id' => '246',
        'name' => '查看个人标签',
        'module' => 'user_tag',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      97 => 
      array (
        'id' => '247',
        'name' => '修改个人标签',
        'module' => 'user_tag',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      98 => 
      array (
        'id' => '248',
        'name' => '修改关于我们设置',
        'module' => 'web_info',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      99 => 
      array (
        'id' => '249',
        'name' => '执行删除公告操作',
        'module' => 'notice',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      100 => 
      array (
        'id' => '250',
        'name' => '查看编辑公告页面',
        'module' => 'notice',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      101 => 
      array (
        'id' => '251',
        'name' => '查看微群分类',
        'module' => 'qun',
        'action' => 'category',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      102 => 
      array (
        'id' => '252',
        'name' => '查看微群等级',
        'module' => 'qun',
        'action' => 'level',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      103 => 
      array (
        'id' => '253',
        'name' => '查看微群策略',
        'module' => 'qun',
        'action' => 'ploy',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      104 => 
      array (
        'id' => '254',
        'name' => '查看微群管理',
        'module' => 'qun',
        'action' => 'manage',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      105 => 
      array (
        'id' => '255',
        'name' => '查看微群设置',
        'module' => 'qun',
        'action' => 'setting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      106 => 
      array (
        'id' => '256',
        'name' => '修改微群设置',
        'module' => 'qun',
        'action' => 'dosetting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      107 => 
      array (
        'id' => '257',
        'name' => '修改微群分类',
        'module' => 'qun',
        'action' => 'docategory',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      108 => 
      array (
        'id' => '258',
        'name' => '修改微博等级',
        'module' => 'qun',
        'action' => 'dolevel',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      109 => 
      array (
        'id' => '259',
        'name' => '修改微群策略',
        'module' => 'qun',
        'action' => 'doploy',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      110 => 
      array (
        'id' => '260',
        'name' => '执行微群管理',
        'module' => 'qun',
        'action' => 'domanage',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      111 => 
      array (
        'id' => '261',
        'name' => '查看用户搜索结果',
        'module' => 'member',
        'action' => 'dosearch',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      112 => 
      array (
        'id' => '262',
        'name' => '修改用户信息',
        'module' => 'member',
        'action' => 'domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      113 => 
      array (
        'id' => '263',
        'name' => '执行删除用户操作',
        'module' => 'member',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      114 => 
      array (
        'id' => '264',
        'name' => '搜索在线用户',
        'module' => 'sessions',
        'action' => 'search',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      115 => 
      array (
        'id' => '265',
        'name' => '添加勋章',
        'module' => 'medal',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      116 => 
      array (
        'id' => '267',
        'name' => '修改勋章',
        'module' => 'medal',
        'action' => 'modify|domodify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      117 => 
      array (
        'id' => '268',
        'name' => '删除勋章',
        'module' => 'medal',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      118 => 
      array (
        'id' => '269',
        'name' => '添加VIP认证',
        'module' => 'vipintro',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      119 => 
      array (
        'id' => '270',
        'name' => '取消VIP谁',
        'module' => 'vipintro',
        'action' => 'open_validate',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      120 => 
      array (
        'id' => '271',
        'name' => '修改VIP认证',
        'module' => 'vipintro',
        'action' => 'modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      121 => 
      array (
        'id' => '273',
        'name' => '查看我的首页',
        'module' => 'topic',
        'action' => 'myhome',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      122 => 
      array (
        'id' => '274',
        'name' => '查看TA关注的用户',
        'module' => 'topic',
        'action' => 'follow',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      123 => 
      array (
        'id' => '275',
        'name' => '查看关注TA的用户',
        'module' => 'topic',
        'action' => 'fans',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      124 => 
      array (
        'id' => '276',
        'name' => '设置我的模板',
        'module' => 'theme',
        'action' => 'do_modify',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      125 => 
      array (
        'id' => '281',
        'name' => '查看昵称找人页面',
        'module' => 'search',
        'action' => 'user',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      126 => 
      array (
        'id' => '282',
        'name' => '查看标签找人页面',
        'module' => 'search',
        'action' => 'usertag',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      127 => 
      array (
        'id' => '283',
        'name' => '查看关键词找微博页面',
        'module' => 'search',
        'action' => 'topic',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      128 => 
      array (
        'id' => '284',
        'name' => '查看话题找微博页面',
        'module' => 'search',
        'action' => 'tag',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      129 => 
      array (
        'id' => '285',
        'name' => '查看关键词找投票页面',
        'module' => 'search',
        'action' => 'vote',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      130 => 
      array (
        'id' => '286',
        'name' => '微博秀页面',
        'module' => 'show',
        'action' => 'show',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      131 => 
      array (
        'id' => '288',
        'name' => '查看媒体汇页面',
        'module' => 'other',
        'action' => 'media',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      132 => 
      array (
        'id' => '289',
        'name' => '查看达人榜页面',
        'module' => 'topic',
        'action' => 'top',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      133 => 
      array (
        'id' => '290',
        'name' => '查看最新发布的微博',
        'module' => 'topic',
        'action' => 'new',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      134 => 
      array (
        'id' => '291',
        'name' => '查看最新评论的微博',
        'module' => 'topic',
        'action' => 'newreply',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      135 => 
      array (
        'id' => '292',
        'name' => '查看我的勋章页面',
        'module' => 'settings',
        'action' => 'user_medal',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      136 => 
      array (
        'id' => '293',
        'name' => '查看我的资料页面',
        'module' => 'settings',
        'action' => 'base',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      137 => 
      array (
        'id' => '294',
        'name' => '执行修改个人资料操作',
        'module' => 'settings',
        'action' => 'do_modify_profile',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      138 => 
      array (
        'id' => '295',
        'name' => '查看修改头像页面',
        'module' => 'settings',
        'action' => 'face',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      139 => 
      array (
        'id' => '296',
        'name' => '执行头像修改操作',
        'module' => 'settings',
        'action' => 'do_modify_face',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      140 => 
      array (
        'id' => '297',
        'name' => '查看修改密码页面',
        'module' => 'settings',
        'action' => 'secret',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      141 => 
      array (
        'id' => '298',
        'name' => '执行修改密码操作',
        'module' => 'settings',
        'action' => 'do_modify_password',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      142 => 
      array (
        'id' => '299',
        'name' => '查看我的积分',
        'module' => 'settings',
        'action' => 'extcredits',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      143 => 
      array (
        'id' => '300',
        'name' => '查看短信列表',
        'module' => 'pm',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      144 => 
      array (
        'id' => '302',
        'name' => '设置短信为未读',
        'module' => 'pm',
        'action' => 'markunread',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      145 => 
      array (
        'id' => '303',
        'name' => '查看投票',
        'module' => 'vote',
        'action' => 'view',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      146 => 
      array (
        'id' => '304',
        'name' => '话题扩展',
        'module' => 'tag',
        'action' => 'extra',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      147 => 
      array (
        'id' => '305',
        'name' => '话题推介',
        'module' => 'tag',
        'action' => 'recommend',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      148 => 
      array (
        'id' => '306',
        'name' => '话题列表',
        'module' => 'tag',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      149 => 
      array (
        'id' => '307',
        'name' => '编辑话题推介',
        'module' => 'tag',
        'action' => 'do_recommend',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      150 => 
      array (
        'id' => '308',
        'name' => '编辑话题扩展',
        'module' => 'tag',
        'action' => 'add_extra',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      151 => 
      array (
        'id' => '311',
        'name' => '查看导航设置',
        'module' => 'setting',
        'action' => 'navigation',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      152 => 
      array (
        'id' => '315',
        'name' => '查看活动管理',
        'module' => 'event',
        'action' => 'manage',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      153 => 
      array (
        'id' => '317',
        'name' => '修改导航设置',
        'module' => 'setting',
        'action' => 'do_navigation',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      154 => 
      array (
        'id' => '318',
        'name' => '设置默认关注和推介',
        'module' => 'setting',
        'action' => 'do_regfollow',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      155 => 
      array (
        'id' => '319',
        'name' => '查看短信用户',
        'module' => 'sms',
        'action' => 'list',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      156 => 
      array (
        'id' => '320',
        'name' => '导出短信用户',
        'module' => 'sms',
        'action' => 'export_to_excel',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      157 => 
      array (
        'id' => '321',
        'name' => '删除活动',
        'module' => 'event',
        'action' => 'delete',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      158 => 
      array (
        'id' => '323',
        'name' => '查看插件列表',
        'module' => 'plugin',
        'action' => 'main',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      159 => 
      array (
        'id' => '324',
        'name' => '插件安装',
        'module' => 'plugin',
        'action' => 'add',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      160 => 
      array (
        'id' => '325',
        'name' => '设计插件',
        'module' => 'plugin',
        'action' => 'design|adddesign',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      161 => 
      array (
        'id' => '327',
        'name' => '启用插件',
        'module' => 'plugin',
        'action' => 'action',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      162 => 
      array (
        'id' => '328',
        'name' => '卸载插件',
        'module' => 'plugin',
        'action' => 'uninstall',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      163 => 
      array (
        'id' => '329',
        'name' => '导出所有用户',
        'module' => 'member',
        'action' => 'export_all_user',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      164 => 
      array (
        'id' => '330',
        'name' => '微博墙控制页',
        'module' => 'wall',
        'action' => 'control',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      165 => 
      array (
        'id' => '340',
        'name' => '创建群',
        'module' => 'qun',
        'action' => 'create|docreate',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '0',
      ),
      166 => 
      array (
        'id' => '361',
        'name' => '查看分类管理',
        'module' => 'fenlei',
        'action' => 'manage',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
      167 => 
      array (
        'id' => '363',
        'name' => '修改API设置',
        'module' => 'api',
        'action' => 'do_modify_setting',
        'describe' => '',
        'message' => '',
        'allow_all' => '0',
        'credit_require' => '',
        'credit_update' => '',
        'php_code' => '',
        'log' => '0',
        'is_admin' => '1',
      ),
    ),
  ),
  'role' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '1',
        'name' => '游客',
        'creditshigher' => '0',
        'creditslower' => '0',
        'privilege' => '50,51,273,274,275,281,282,283,284,285,286,288,289,290,291,292,293,295,297,299,300,303',
        'type' => 'normal',
        'rank' => '2',
        'discuz_group_id' => '7',
      ),
      1 => 
      array (
        'id' => '2',
        'name' => '管理员',
        'creditshigher' => '0',
        'creditslower' => '0',
        'privilege' => '7,8,9,11,13,50,51,84,88,89,90,91,92,93,101,102,106,107,108,111,115,123,125,126,132,133,134,135,136,137,138,139,154,158,159,169,172,176,182,183,184,186,187,188,189,190,191,192,193,194,195,196,197,198,200,201,202,204,205,206,208,210,211,212,213,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,267,268,269,270,271,273,274,275,276,281,282,283,284,285,286,288,289,290,291,292,293,294,295,296,297,298,299,300,302,303,304,305,306,307,308,311,315,317,318,319,320,321,323,324,325,327,328,329,330,340,361,363',
        'type' => 'admin',
        'rank' => '1',
        'discuz_group_id' => '1',
      ),
      2 => 
      array (
        'id' => '3',
        'name' => '普通会员',
        'creditshigher' => '0',
        'creditslower' => '1000',
        'privilege' => '7,50,51,176,193,194,195,196,197,198,273,274,275,276,281,282,283,284,285,286,288,289,290,291,292,293,294,295,296,297,298,299,300,302,303,330,340',
        'type' => 'normal',
        'rank' => '2',
        'discuz_group_id' => '10',
      ),
      3 => 
      array (
        'id' => '4',
        'name' => '禁言组',
        'creditshigher' => '0',
        'creditslower' => '0',
        'privilege' => '50,51',
        'type' => 'normal',
        'rank' => '0',
        'discuz_group_id' => '10',
      ),
      4 => 
      array (
        'id' => '5',
        'name' => '等验证会员',
        'creditshigher' => '0',
        'creditslower' => '0',
        'privilege' => '50,51',
        'type' => 'normal',
        'rank' => '0',
        'discuz_group_id' => '8',
      ),
      5 => 
      array (
        'id' => '7',
        'name' => '后台查看',
        'creditshigher' => '0',
        'creditslower' => '0',
        'privilege' => '7,8,11,13,50,51,88,92,125,126,133,135,137,139,176,192,193,194,195,196,197,198,200,202,205,211,213,215,216,217,218,219,220,221,222,223,226,228,230,235,236,238,241,246,250,251,252,253,254,255,273,274,275,276,281,282,283,284,285,286,288,289,290,291,292,293,294,295,296,297,298,299,300,302,303,304,305,306,311,319,330,340',
        'type' => 'admin',
        'rank' => '0',
        'discuz_group_id' => '10',
      ),
    ),
  ),
  'medal' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '1',
        'medal_img' => './images/medal/1301651267/1_o.jpg',
        'medal_img2' => './images/medal/1301651267/1_s.jpg',
        'medal_name' => '微博达人',
        'medal_depict' => '连续3天发布原创微博，就能获得微博达人勋章',
        'medal_count' => '0',
        'is_open' => '1',
        'conditions' => 'a:4:{s:4:"type";s:5:"topic";s:3:"day";s:1:"3";s:6:"endday";s:0:"";s:7:"tagname";N;}',
        'dateline' => '1301651267',
      ),
      1 => 
      array (
        'id' => '2',
        'medal_img' => './images/medal/1301651359/2_o.jpg',
        'medal_img2' => './images/medal/1301651359/2_s.jpg',
        'medal_name' => '评论专家',
        'medal_depict' => '连续3天对他人微博进行评论，就能获得”评论专家“勋章',
        'medal_count' => '0',
        'is_open' => '1',
        'conditions' => 'a:4:{s:4:"type";s:5:"reply";s:3:"day";s:1:"3";s:6:"endday";N;s:7:"tagname";N;}',
        'dateline' => '1301651359',
      ),
    ),
  ),
  'credits_rule' => 
  array (
    'key' => 'action',
    'datas' => 
    array (
      0 => 
      array (
        'rid' => '1',
        'rulename' => '发布原创微博',
        'action' => 'topic',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '10',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '2',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      1 => 
      array (
        'rid' => '7',
        'rulename' => '发送短消息',
        'action' => 'pm',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '1',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      2 => 
      array (
        'rid' => '3',
        'rulename' => '关注好友',
        'action' => 'buddy',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '10',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '1',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      3 => 
      array (
        'rid' => '8',
        'rulename' => '设置头像',
        'action' => 'face',
        'cycletype' => '0',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '10',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      4 => 
      array (
        'rid' => '9',
        'rulename' => 'VIP认证',
        'action' => 'vip',
        'cycletype' => '0',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '20',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      5 => 
      array (
        'rid' => '6',
        'rulename' => '每天登录',
        'action' => 'login',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '2',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      6 => 
      array (
        'rid' => '2',
        'rulename' => '评论或转发微博',
        'action' => 'reply',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '10',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '1',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      7 => 
      array (
        'rid' => '4',
        'rulename' => '邀请注册',
        'action' => 'register',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '10',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '10',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      8 => 
      array (
        'rid' => '10',
        'rulename' => '发布指定话题',
        'action' => '_T84202031',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '2',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '5',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '新人报到',
      ),
      9 => 
      array (
        'rid' => '11',
        'rulename' => '关注指定用户',
        'action' => '_U-2012344970',
        'cycletype' => '0',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '5',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => 'admin',
      ),
      10 => 
      array (
        'rid' => '12',
        'rulename' => '删除微博',
        'action' => 'topic_del',
        'cycletype' => '4',
        'cycletime' => '0',
        'rewardnum' => '0',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '-5',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      11 => 
      array (
        'rid' => '13',
        'rulename' => '取消关注好友',
        'action' => 'buddy_del',
        'cycletype' => '4',
        'cycletime' => '0',
        'rewardnum' => '0',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '-5',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      12 => 
      array (
        'rid' => '15',
        'rulename' => '发布指定话题',
        'action' => '_T',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '0',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      13 => 
      array (
        'rid' => '16',
        'rulename' => '关注指定用户',
        'action' => '_U',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '1',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '0',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      14 => 
      array (
        'rid' => '17',
        'rulename' => '发起投票',
        'action' => 'vote_add',
        'cycletype' => '1',
        'cycletime' => '0',
        'rewardnum' => '10',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '2',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
      15 => 
      array (
        'rid' => '18',
        'rulename' => '删除投票',
        'action' => 'vote_del',
        'cycletype' => '4',
        'cycletime' => '0',
        'rewardnum' => '0',
        'norepeat' => '0',
        'extcredits1' => '0',
        'extcredits2' => '-5',
        'extcredits3' => '0',
        'extcredits4' => '0',
        'extcredits5' => '0',
        'extcredits6' => '0',
        'extcredits7' => '0',
        'extcredits8' => '0',
        'related' => '',
      ),
    ),
  ),
  'event_info' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '1',
        'need_info' => 'a:6:{i:2;a:5:{s:2:"id";s:1:"2";s:4:"name";s:8:"真实姓名";s:9:"form_type";s:4:"text";s:8:"form_set";s:0:"";s:5:"ename";s:8:"realname";}i:3;a:5:{s:2:"id";s:1:"3";s:4:"name";s:4:"性别";s:9:"form_type";s:6:"select";s:8:"form_set";s:6:"男
女";s:5:"ename";s:4:"sexy";}i:4;a:5:{s:2:"id";s:1:"4";s:4:"name";s:8:"手机号码";s:9:"form_type";s:4:"text";s:8:"form_set";s:0:"";s:5:"ename";s:8:"telphone";}i:24;a:5:{s:2:"id";s:2:"24";s:4:"name";s:2:"QQ";s:9:"form_type";s:4:"text";s:8:"form_set";s:0:"";s:5:"ename";s:2:"qq";}i:27;a:5:{s:2:"id";s:2:"27";s:4:"name";s:8:"自我介绍";s:9:"form_type";s:4:"text";s:8:"form_set";s:0:"";s:5:"ename";s:4:"show";}i:29;a:5:{s:2:"id";s:2:"29";s:4:"name";s:8:"联系地址";s:9:"form_type";s:4:"text";s:8:"form_set";s:0:"";s:5:"ename";s:7:"linkadd";}}',
      ),
    ),
  ),
  'event_needinfo' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '2',
        'name' => '真实姓名',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'realname',
      ),
      1 => 
      array (
        'id' => '3',
        'name' => '性别',
        'form_type' => 'select',
        'form_set' => '男
女',
        'ename' => 'sexy',
      ),
      2 => 
      array (
        'id' => '4',
        'name' => '手机号码',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'telphone',
      ),
      3 => 
      array (
        'id' => '5',
        'name' => '生日',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'birthday',
      ),
      4 => 
      array (
        'id' => '6',
        'name' => '证件号',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'card_id',
      ),
      5 => 
      array (
        'id' => '7',
        'name' => '邮寄地址',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'address',
      ),
      6 => 
      array (
        'id' => '8',
        'name' => '邮编',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'number',
      ),
      7 => 
      array (
        'id' => '9',
        'name' => '国籍',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'nation',
      ),
      8 => 
      array (
        'id' => '10',
        'name' => '出生地',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'birthadd',
      ),
      9 => 
      array (
        'id' => '11',
        'name' => '居住地',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'liveadd',
      ),
      10 => 
      array (
        'id' => '12',
        'name' => '毕业学校',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'school',
      ),
      11 => 
      array (
        'id' => '13',
        'name' => '学历',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'record',
      ),
      12 => 
      array (
        'id' => '14',
        'name' => '公司',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'company',
      ),
      13 => 
      array (
        'id' => '15',
        'name' => '职业',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'job',
      ),
      14 => 
      array (
        'id' => '16',
        'name' => '职位',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'position',
      ),
      15 => 
      array (
        'id' => '17',
        'name' => '年收入',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'money',
      ),
      16 => 
      array (
        'id' => '18',
        'name' => '情感状态',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'status',
      ),
      17 => 
      array (
        'id' => '19',
        'name' => '交友目的',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'goal',
      ),
      18 => 
      array (
        'id' => '20',
        'name' => '血型',
        'form_type' => 'select',
        'form_set' => 'A
B
AB
O
其他',
        'ename' => 'blood',
      ),
      19 => 
      array (
        'id' => '21',
        'name' => '身高',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'height',
      ),
      20 => 
      array (
        'id' => '22',
        'name' => '体重',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'weight',
      ),
      21 => 
      array (
        'id' => '23',
        'name' => '支付宝',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'taobao',
      ),
      22 => 
      array (
        'id' => '24',
        'name' => 'QQ',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'qq',
      ),
      23 => 
      array (
        'id' => '25',
        'name' => 'MSN',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'msn',
      ),
      24 => 
      array (
        'id' => '26',
        'name' => '个人主页',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'url',
      ),
      25 => 
      array (
        'id' => '27',
        'name' => '自我介绍',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'show',
      ),
      26 => 
      array (
        'id' => '28',
        'name' => '兴趣爱好',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'like',
      ),
      27 => 
      array (
        'id' => '1',
        'name' => '联系地址',
        'form_type' => 'text',
        'form_set' => '',
        'ename' => 'linkadd',
      ),
    ),
  ),
  'event_sort' => 
  array (
    'key' => 'id',
    'datas' => 
    array (
      0 => 
      array (
        'id' => '1',
        'type' => '演出/电影',
      ),
      1 => 
      array (
        'id' => '2',
        'type' => '生活/聚会',
      ),
      2 => 
      array (
        'id' => '3',
        'type' => '旅行/户外',
      ),
      3 => 
      array (
        'id' => '4',
        'type' => '展览/沙龙',
      ),
      4 => 
      array (
        'id' => '5',
        'type' => '体育/健身',
      ),
      5 => 
      array (
        'id' => '6',
        'type' => '公益/环保',
      ),
      6 => 
      array (
        'id' => '7',
        'type' => '派对/夜店',
      ),
      7 => 
      array (
        'id' => '8',
        'type' => '作品征集',
      ),
      8 => 
      array (
        'id' => '9',
        'type' => '市集/游园',
      ),
      9 => 
      array (
        'id' => '10',
        'type' => '打折/促销',
      ),
      10 => 
      array (
        'id' => '11',
        'type' => '其他',
      ),
    ),
  ),
) ; ?>